doc/happy.xml

Hi, during reading I observed some errors in the documentation and fixed them now. This includes
- typos
- Unwanted indentation of code examples
- Missing option descriptions
- Avoidance of list items started with a blank line in PDF output (caused by `indexterm` before `para`).
I'd be happy if my changes would be merged.
Attention: I built the PDF myself but got the following warnings:
```
Don't know what gentext to create for xref to: "listitem" (linkend=item-default-backend)
Don't know what gentext to create for xref to: "listitem" (linkend=item-default-backend)
```
So you may have a closer look at this.

Improved documentation

---

src/Grammar.lhs
src/ParamRules.hs

This pull request adds the ability to create type signatures for parameterized rules.  This, along with a slight change to the way that parameterized rule instance names are generated allows parameterized rules to be used with GLR parsers.
It works by substituting the formal parameter names in parameterized rule type signatures with the types associated with the actual parameters.  Only parameter names that start with a lowercase letter are substituted.  Actual parameters that correspond with non-terminals are substituted with the non-terminal's type (which must be defined).  Actual parameters that correspond with terminals are substituted with the token type, which will not work correctly when the terminal uses a `$$` in its token pattern.  For this to work, there would need to be a way …

Type signature on parameterized rules

---

src/ProduceCode.lhs

Solves https://github.com/simonmar/happy/issues/35

Fix parse error when doing lookahead with %^ and %%

---

examples/Calc.ly

Fix spello in examples/Calc.ly

---

src/LALR.lhs

Two space leaks, squashed by using a strict accumulator.

Space leaks

---

src/LALR.lhs

As part of my efforts to investigate space leaks, I ended up at the `fold_lookahead` function, which I rewrote as below. I offer this as an entirely separate patch because there are good reasons you might want to not merge it. Advantages:
* Reduces stack usage from > 1Mb to < 1Kb.
* Algorithm more directly states what it does.
* Better time complexity - previously it was a combination of insertion sort on the Int and a weird order-changing nub construction on the Lr0Item.
* Passes all the tests.
Disadvantages:
* Has no meaningful time difference - my tests are with 0.03s.
* Produces different output since the list is in a different order. I believe the results are equivalent, but you will need to say for sure.

Rewrite fold_lookahead to avoid using the stack and improve time complexity

---

tests/Makefile

Windows writes out files to stdout and stderr with Windows newlines in, but the sample files are Linux newlines. To make sure `diff` doesn't fail we ignore the whitespace, which includes ignoring newline differences.

Make the test suite work on Windows

---

src/ProduceCode.lhs

Adding the type signature takes care of this error:
```
../dist/build/happy/happy --strict --template=.. -g monad002.ly -o monad002.g.hs
ghc -hide-all-packages -package base -package array -package mtl -Werror -fforce-recomp  monad002.g.hs -o monad002.g.bin
[1 of 1] Compiling Main             ( monad002.g.hs, monad002.g.o )
monad002.g.hs:311:22:
Couldn't match kind ‘*’ with ‘#’
When matching types
t0 :: *
Happy_GHC_Exts.Int# :: #
```
And 'cabal test' pass. Tested with GHC 7.8.4 too.
Signed-off-by: Dan Aloni <dan@kernelim.com>

Fix ProduceCode.hs for GHC 7.10.x

---

doc/happy.xml
src/AbsSyn.lhs
src/Grammar.lhs
src/Lexer.lhs
src/Main.lhs
src/Parser.ly
src/ProduceCode.lhs
templates/GenericTemplate.hs
tests/Makefile
tests/monaderror-explist.y

People asked for a patch upstream - so here's the place to start a discussion.
In this change, I've made sure that 'cabal test' still passes, and the interface to unmodified users is preserved. But you would probably have more comments.

RFC: On parse error - show the next possible tokens

---

templates/GenericTemplate.hs

Even with an exact type signature for `unbox_int `and `indexShortOffAddr` GHC 7.6 fails to realize the type for the second parameter of indexShortOffAddr which needs to be of unboxed kind '#' instead
of boxed '*'.
```
Couldn't match kind `#' against `*'
In the second argument of `indexShortOffAddr', namely
`(unbox_int $ bit `div` 16)'
```
It's probably due to `div`. Figured out we can use unboxed right shift instead, to get it straight.
Tested with GHC 7.6.3, GHC 7.8.4, and GHC 7.10.3.
Signed-off-by: Dan Aloni <dan@kernelim.com>

GenericTemplate.hs: workaround GHC 7.6 type checking failure

---

src/Main.lhs

The commit adding the pretty printing functionality accidentally
broke the `-i` flag.   `-p` was also broken, in that it would print
to `stdout` all the time.
Should be fixed now, sorry for the breakage.

Fix broken command line options.

---

src/ProduceCode.lhs
tests/Makefile
tests/typeclass_monad001.y
tests/typeclass_monad002.ly
tests/typeclass_monad_lexer.y

This pull requests causes happy to generate some new signatures that allow typeclasses to be used in monadic parsers.  This makes no changes to actual code; it only generates some signatures.
This patch only generates signature for parsers that combine `%monad` and `%lexer` directives.  There appear to be some non-trivial issues that arise when `%monad` is used without `%lexer`.
This has been verified to work with a complex parser (and in conjunction with the corresponding alex pull request) here:
https://github.com/saltlang/saltlang/blob/typeclass_parser/src/salt/Language/Salt/Surface/Parser.y
The resulting lexer/parser combination operates inside a monad completely described by typeclasses.

Add signature generation for using typeclasses in parsers

---

src/Main.lhs
src/PrettyGrammar.hs

This should be functionally equivalent to the previous version, it just removes an unused import, an unused variable, and a shadowed variable.

Clean up warnings from pretty-grammar feature

---

happy.cabal

See http://hackage.haskell.org/package/happy-1.19.5/revisions/
Stil couldn't get it to build with:
```
$ stack init
$ stack build --nix
mtl-2.2.1: configure
mtl-2.2.1: build
mtl-2.2.1: copy/register
happy-1.19.6: configure (exe)
[1 of 2] Compiling Main             ( /home/ielectric/dev/happy/Setup.lhs, /home/ielectric/dev/happy/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/setup/Main.o )
[2 of 2] Compiling StackSetupShim   ( /home/ielectric/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/ielectric/dev/happy/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/setup/StackSetupShim.o )
Linking /home/ielectric/dev/happy/.stack-work/dist/x86_64-linux-nix/Cabal-1.24.2.0/setup/setup ...
Configuring happy-1.19.6...
happy-1.19.6: build (exe)
Preprocessing executable 'happy' for happy-1.19.6... …
```

Catch up with cabal modifications on hackage

---

src/ProduceCode.lhs

This should fix #91.
This bug can be triggered by compiling the generated code on any grammar that
* uses `%tokentype` that is _not_ just `Token` (try something like `Token1`)
* makes use of `%lexer`
* is compiled using `-g`

'happyNewToken' now uses the right token type

---

doc/configure.ac

Allow Arch's makepkg to build and install documentation as expected.

Add docbook xml path as currently found in Arch linux.

---

doc/happy.xml

Missing paragraph tags were preventing compilation of documentation.

Fix doc validation errors

---

templates/GenericTemplate.hs
tests/Makefile
tests/bug004.y
tests/issue91.y
tests/issue95.y

The type annotation on `nt` is only needed in the case that `-a` is not enabled. When `-a` is enabled, the type of `nt` is constrained by `PLUS(off,nt)`.
I also added a regression test case (which would previously have failed with just `-gc` enabled). As before, I can't run the test suite automatically, so if Travis fails I'll see what is up.
This fixes #95.

Add types to help GHC infer kind in `happyMonad2Reduce`

---

src/ProduceCode.lhs
templates/GenericTemplate.hs

This fixes https://github.com/simonmar/happy/issues/93.
* Added new variable `happyMinOffset` that is present only when arrays are enabled.
This variable keeps track of the lowest offset value we should ever find in the
values of `happyActOffsets` and `happyGotoOffsets`. That way, if we ever find a
value that is smaller, we know it accidentally wrapped around (and we can correct
for the wraparound).
* Added a check so that if Happy is run with `--ghc` and the offset tables are
actually too large, Happy will fail with an error message instead of generating
bogus code (as it currently does).
Since the negative numbers in offset tables are generally quite small, this
effectively doubles the size of offsets supported.

Support larger offset tables

---

happy.cabal
src/ProduceCode.lhs
templates/GenericTemplate.hs
tests/Makefile
tests/issue93.y

This addresses the comments on https://github.com/simonmar/happy/pull/102. It adds
* a (rather long, but still one file) test case which results in a `happyTable` with more than 2^15 entries. This test case fails before the PR and passes afterwards.
* instead of using `happyMinOffset`, we generate `happyAdjustOffset`, which contains the logic for adjusting offsets only when `--ghc` is enabled _and_ the `happyTable` is more than 2^15 elements long. Otherwise, it does nothing.
Please let me know if anything is amiss. I hope this ties up loose ends from the last PR.

Happy overflow followup

---

src/PrettyGrammar.hs

We now export `<>` from Prelude, which conflicts with the pretty printer.
This came up when trying to compile HEAD with HEAD using hadrian.

Semigroup-Monoid-Proposal

---

happy.cabal

Cabal 2.1.0.0. was shipped with GHC 8.4.1-alpha1 (announced [here](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html)). This PR allows to use this version of Cabal.

Bumped upper version bound for Cabal library

---

happy.cabal

`cabal install` generates the following warning:
```
Warning: Enabling workaround for Main module 'Main' listed in 'other-modules'
illegally!
```
This PR fix this warning.
Tested with:
```
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.2.2
$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library
```

Fixed warning: Main module 'Main' listed in 'other-modules'

---

happy.cabal

This silences the missing-home-module warning.

Add Paths_happy to other-modules

---

happy.cabal

This was already performed on Hackage via revision to unblock GHC 8.4.1 install-plans:
http://hackage.haskell.org/package/happy-1.19.9/revisions/

Relax upper bound on setup:Cabal to allow GHC 8.4.1's Cabal

---

src/AttrGrammarParser.hs
src/Parser.hs

I believe this fixes https://github.com/simonmar/happy/issues/139
As of now, the latest `happy` tarball release will not build with GHC 8.8.1

Apply failP changes to .hs files used for bootstrap

---

Setup.hs
happy.cabal

https://github.com/haskell/cabal/pull/3693 deprecated `rawSystemProgramConf` in favor of `runDbProgram`.

Setup.hs: Compatibility with Cabal-3

---

src/AbsSyn.lhs
src/First.lhs
src/Grammar.lhs
src/Info.lhs
src/LALR.lhs
src/ParamRules.hs
src/Parser.ly
src/PrettyGrammar.hs
src/ProduceCode.lhs
src/ProduceGLRCode.lhs

This commit changes no new functionality, but hopefully it makes the
code more readable and less prone to accidental type confusion. All
refactoring is very mechanical:
* replace type synonyms of large tuples with proper types
* add conservative comments to data types and functions
* add a handful of type signatures

Replace type synonyms with proper types, add docs

---

happy.cabal

This patch removes an unused configuration flag. It has been deprecated for 5 years.

Remove deprecated flag small_base

---

doc/happy.xml
happy.cabal
src/AbsSyn.lhs
src/Grammar.lhs
src/LALR.lhs
src/Lexer.lhs
src/ParamRules.hs
src/Parser.ly
src/PrettyGrammar.hs
tests/Makefile
tests/shift01.y

[GHC Merge Request 1856](https://gitlab.haskell.org/ghc/ghc/merge_requests/1856) resolves shift/reduce conflicts in GHC by using the precedence machinery of `happy`, marking certain rules as `%prec shift`.
However, the downside of this approach is that it requires a listing of all lookahead tokens. With a dedicated pragma `%shift`, we can avoid this.

%shift pragma for lowest priority rules

---

src/Main.lhs

When my grammar fails `%expect`, I almost always debug with `--info`.
However, that doesn't work either until I first comment out the
`%expect`.
Now it will: we postpone the `%expect` check until after the `--info`
and `--pretty` information has been written out.
Fixes #121

`--info`/`--pretty` work despite bad `%expect`

---

src/AbsSyn.lhs
src/Grammar.lhs
src/Parser.ly
src/ProduceCode.lhs
templates/GenericTemplate.hs

This is a less ambitious resolution to https://github.com/simonmar/happy/issues/131 than https://github.com/simonmar/happy/pull/135 was.
The compiler construction course in which the underlying issue arose last year is due to start again now. I see that making a more comprehensive fix, which would prevent problems like this from arising in `happy` again in the future, is stalled in discussion between @Kellador and @simonmar over in https://github.com/simonmar/happy/pull/135. CC'ing @owestphal, who would have to deal with students' problems arising from name clashes between Prelude functions and own functions in the practical part of the course.
The pull request here does the minimal thing. No interface changes (that is, no new cli options) to `happy`, no preprocessor magic, no changes to …

qualify Prelude functions in templates

---

README.md

Installation instructions for development version (#160):
Requires `make sdist` before `cabal install`.

[ fixed #160 ] installation instruction for development version

---

doc/happy.xml

I got the following error when running the monadic and threaded lexers examples in the documentation:
```haskell
• Data constructor not in scope: OK :: a -> E a
• Perhaps you meant ‘Ok’ (line 11)
|
29 |     Ok a     -> OK a
|                 ^^
```
This PR fix these examples.

Documentation: Fixed monadic and threaded lexers examples

---

src/AbsSyn.lhs
src/Grammar.lhs
src/LALR.lhs
src/Lexer.lhs
src/Main.lhs

Hiding this behind CPP is not necessary. GHC supports flags such as `-ddump-tc-trace` and users have no problem with this.

Debug options in all build configurations

---

ChangeLog.md
happy.cabal

Bump versions number and write change log.

Prepare for a release prior to the "big split"

---

packages/frontend/src/Happy/Frontend.hs
packages/frontend/src/Happy/Frontend/AbsSyn.lhs
packages/frontend/src/Happy/Frontend/Mangler.lhs
packages/frontend/src/Happy/Frontend/Parser/Bootstrapped.ly
packages/frontend/src/Happy/Frontend/Parser/Oracle.hs
packages/frontend/src/Happy/Frontend/PrettyGrammar.hs
src/Main.lhs

`BookendedAbsSyn` wraps it to separate the information needed by the
middle parts of happy from the header and footer which are just added
back at the end.
The code looks nicer to me now, with fewer wildcard and @-patterns,
therefore I conclude that this is makes the data structures more natural
for what we are doing.

Split `BookendedAbsSyn` out from `AbsSyn`

---

.gitignore
doc/.gitignore
doc/README.md
doc/configure.ac

Instructions how to build the happy documentation.
Also, adding path to DocBook stylesheets (xsl) when installed on Mac via HomeBrew.

Instructions how to build the happy documentation

---

doc/happy.xml

#228 replaced Ljungloef with Ljunglöf
.html and .pdf generation now correct
@Ericson2314 
can you close https://github.com/haskell/happy/issues/62

use unicode

---

packages/frontend/src/Happy/Frontend/ParamRules.hs

It fixes building `happy` with `mtl` >=v2.3 (https://github.com/haskell/happy/issues/236)

Fix build with mtl v2.3

---

CONTRIBUTING.rst
ChangeLog.md
README.md
doc/contributing.rst
doc/index.rst
doc/introduction.rst
doc/obtaining.rst

The idea is that the docs should the source of truth, and be able to replace the website.
Information from the read-me is also moved to the docs.
The `CONTRIBUTING.rst` symlink is intended to do a thing on GitHub (see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors), but I am not sure how to confirm it will short of merging this PR.
Some bits taken from this analogous PR for Alex: https://github.com/haskell/alex/pull/219

Deduplicate docs, prepare to get rid of website

---

.github/haskell-ci.patch
.github/workflows/haskell-ci.yml
DEVELOPER.md
happy.cabal
packages/backend-glr/happy-backend-glr.cabal
packages/backend-lalr/happy-backend-lalr.cabal
packages/codegen-common/happy-codegen-common.cabal
packages/frontend/happy-frontend.cabal
packages/grammar/happy-grammar.cabal
packages/tabular/happy-tabular.cabal

Update to the latest Haskell CI (0.15.20230203)
- update `tested-with` in the `.cabal` files
- update the patch to apply cleanly to the latest Haskell-CI generated workflow
- update developer manual with step to update the patch
- update `haskell-ci.yml`
I split this into several patches as some of these could be applied to the `release-1.20` branch, but not all.  See:
- #248

Update to the latest Haskell CI (0.15.20230203)

---

packages/frontend/happy-frontend.cabal
packages/frontend/src/Happy/Frontend/AttrGrammar/Mangler.lhs
packages/frontend/src/Happy/Frontend/Mangler.lhs
packages/frontend/src/Happy/Frontend/Mangler/Monad.lhs

We previously had a lot of `#ifdef HAPPY_BOOTSTRAP` to support mangling with and without attribute grammar support. Now that module is broken up so that we need less.
This hopefully makes the code easier to understand and maintain.

Reduce the amount of CPP for attribute grammar support

---

.readthedocs.yaml
doc/conf.py
doc/requirements.txt

Readthedocs: add explicit requirement sphinx_rtd_theme

---

happy.cabal
test.hs

Compile testsuite with -threaded (#264)

---

packages/backend-glr/data/GLR_Lib.hs
packages/backend-lalr/data/HappyTemplate.hs
packages/backend-lalr/src/Happy/Backend/LALR.hs
packages/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
src/Main.lhs
tests/Makefile

This PR removes all the code related `-g/--ghc` args, making it on by default, removing all conditional code based on it, so that the generated parsers can only build with GHC compiler.
@int-index @Ericson2314 @sgraf812 This PR is has another commit, from #276, ignore it for now, I based the second commit on it just to make merging both easier, rather than doing rebase/merge later.

Support GHC as the only compiler to build happy generated parsers

---

packages/backend-lalr/data/HappyTemplate.hs
packages/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs

This PR refactors happyDoActions into several smaller functions, changes how the parsing tables are constructed, using 32-bit integers instead of 16-bit integers.

Refactor happyDoActions

---

happy.cabal

All the incomplete matches are in fact safe. The warnings only add noise.
https://github.com/haskell/happy/pull/247 is related, but a non-solution.

Suppress warnings for incomplete uni-patterns and partial use of head 

---

ChangeLog.md
happy.cabal
packages/backend-lalr/src/Happy/Backend/LALR.hs

Use -XNoStrictData in generated parser (#273)

---

.gitignore
ChangeLog.md
doc/contributing.rst
doc/introduction.rst

I mostly completed the ChangeLog from looking at [this list](https://github.com/haskell/happy/commits/master?since=2021-10-17&until=2024-09-16).
If someone would give me the necessary hackage credentials (user sgraf812), I would be happy to do the hackage release.
I would just use `nix run nixpkgs#hkgr -- publish` to do so. Or is there some documented procedure one should follow for releases? At any rate, we should document the procedure. Perhaps in `CONTRIBUTING.rst`?

Release preparations for 2.0

---

ChangeLog.md
happy.cabal
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/happy-lib.cabal

2 spaces forced a breaking change on GHC. Fixes #303.
Let me try on GHC before merging.

Generate 8 spaces instead 2 spaces (#303)

---

app/Main.lhs
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/frontend/src/Happy/Frontend/AbsSyn.lhs
lib/frontend/src/Happy/Frontend/AttrGrammar/Mangler.lhs
lib/frontend/src/Happy/Frontend/Mangler.lhs
lib/grammar/src/Happy/Grammar.lhs

I want to better separate the attribute grammar stuff
- Much code doesn't care at all (rightly or wrongly), so we can use the types to track which does does.
- Only one backend supports it, it should be ill-typed to try to use it with the other backend. (This is not yet achieved, but step in that directly.
- Generally trying to slim down `Grammar` to just the essentials, the grammar itself.

Attribute grammar cleanup

---

app/Main.lhs
lib/tabular/src/Happy/Tabular/Info.lhs

We're already taking the entire grammar, so we don't need to separately take a field of the grammar.

Remove redundant paramater

---

lib/backend-glr/src/Happy/Backend/GLR/ProduceCode.lhs
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/frontend/boot-src/Parser.ly
lib/frontend/src/Happy/Frontend/AbsSyn.lhs
lib/frontend/src/Happy/Frontend/Parser.hs
lib/grammar/src/Happy/Grammar.lhs
lib/grammar/src/Happy/Grammar/ExpressionWithHole.hs
lib/happy-lib.cabal
lib/tabular/src/Happy/Tabular/Info.lhs

Instead of deferring the handling of `$$` to the backends, properly parse the `$$` syntax up front, and store the result in the AST.
Note that the GLR backend was improperly substituting the `$$` twice. Now that we have better types, this was surfaced as type error, and then removed.
Fixes #295

Improve the abstract syntax for tokens

---

lib/backend-lalr/src/Happy/Backend/LALR.hs
tests/Makefile

Add -XPatternGuards and build tests with -XHaskell98 (#309)

---

lib/backend-glr/src/Happy/Backend/GLR/ProduceCode.lhs
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/frontend/src/Happy/Frontend/AttrGrammar.lhs
lib/frontend/src/Happy/Frontend/AttrGrammar/Mangler.lhs
lib/frontend/src/Happy/Frontend/Mangler.lhs
lib/grammar/src/Happy/Grammar.lhs
lib/tabular/src/Happy/Tabular/First.lhs
lib/tabular/src/Happy/Tabular/LALR.lhs
lib/tabular/src/Happy/Tabular/NameSet.hs

The GLR backend has me stuck, but I think I got the rest.
Depends on #296

Make Name a newtype

---

ChangeLog.md
doc/syntax.rst
happy.cabal
lib/backend-lalr/src/Happy/Backend/LALR.hs
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/data/HappyTemplate.hs
lib/frontend/boot-src/Parser.ly
lib/frontend/src/Happy/Frontend/AbsSyn.lhs
lib/frontend/src/Happy/Frontend/AttrGrammar/Parser.hs
lib/frontend/src/Happy/Frontend/Parser.hs
lib/happy-lib.cabal
tests/issue131.y

This is in order to undo a breaking change caused by users writing `import Prelude hiding (null)`.
Fixes #325.

Do not use Prelude; concoct our own Happy_Prelude alias (#325)

---

happy.cabal
lib/grammar/src/Happy/Grammar.lhs
lib/happy-lib.cabal
lib/tabular/src/Happy/Tabular/LALR.lhs
tests/catch-shift-reduce.y

When the current token is the catch token, we never reduce; we only ever shift (see the [user's guide](https://haskell-happy.readthedocs.io/en/latest/using.html#resumptive-parsing-with-catch) for how `catch` works). More precisely, the mechanism considers multiple situations in which the `catch` token can be shifted in parallel, including situations that are reachable via reductions. Hence it does not make sense to report shift/reduce conflicts involving the catch token: Error resumption mode will only ever try to shift it.
The solution implemented in this patch is not to generate conflicting `LR'Reduce` actions in the first place by deleting the `catch` token from the lookahead sets of LR1 items.

Auto-resolve shift/reduce conflicts involving the catch token

---

lib/backend-glr/src/Happy/Backend/GLR.hs
lib/backend-glr/src/Happy/Backend/GLR/ProduceCode.lhs
lib/backend-lalr/src/Happy/Backend/LALR.hs
lib/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
lib/happy-lib.cabal

Not only do we need to move the module, we also need to reexport it under a different name lest we get an unhelpful error suggesting to add `Paths_happy_lib` to the other-modules section of `backend-{lalr,glr}`.
It is likely that this change will also fix `cabal v1-install happy` (#315), which was broken since happy-2.0.
Fixes #328.

Move Paths_happy_lib into `tabular` to prevent a Cabal bug concerning --libsubdir (#328)
