haskell/happy

- doc/happy.xml
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>
> Manual entry for info files.

- src/LALR.lhs
Sorry Simon, I missed an import from https://github.com/simonmar/happy/pull/64 :frowning:
> Add a missing import following #64

- .travis.yml
This should fix the travis buld.
> .travis.yml: Add path to cabal executable

- doc/happy.xml
I found some minor issues while reading the happy manual. This PR fixes them.
(new PR to cleanup the commits)
> Minor issues/typos in manual

- tests/Makefile
- tests/bug003.y
I don't have the right soup to test this (I don't have any global version of `ghc` or `cabal` installed, I get by with `stack`) but the CI should tell us whether I correctly added a test case.
> Added a regression test for #91

- src/ParseMonad.hs
> Remove '>>= return'

- happy.cabal
- src/AttrGrammarParser.ly
- src/Lexer.lhs
- src/ParseMonad.hs
- src/Parser.ly
I'm not 100% sure what GHC 8.8.1 will look like when released, but in any case: this fixes it so that it works with the GHC 8.8.1 in hvr's ppa.
> Fix for GHC 8.8.1

- CHANGES
- happy.cabal
> Bump to 1.20.0

- tests/Makefile
> Remove sandboxing reminants from test makefile

- .travis.yml
- Makefile
- happy.cabal
- tests/Makefile
- tests/monaderror-explist.y
- tests/monaderror.y
- tests/typeclass_monad_lexer.y
- Pin cabal-install 3.4
- Test with more GHCs
- Use `v2-` not `new-` with Cabal commands
> Sync build infra with Alex

- src/GenUtils.lhs
- src/Grammar.lhs
- src/Parser/Oracle.hs
- src/ProduceCode.lhs
- src/ProduceGLRCode.lhs
I was having trouble building `happy` from the current state of the repository. These are the changes I needed to make:
- fix some of the problematic imports, in particular adding explicit import lists to `Data.List` imports to avoid name clashes,
- add local type signatures to `match` functions in `Parser.Oracle`, as I was getting type errors without them.
> Small compatibility update

- README.md
Now I must admit I'm getting cold feet and feel like I should maybe see how hard the cabal-install issue to fix is, but it is a time-intensive investigation
> Update readme, mainly with build instructions

- src/Main.lhs
Float GLR bindings into branch, and make literate headings consistent.
> Small cleanup of main

- doc/happy.xml
fix for https://github.com/haskell/happy/issues/62
Göteborgs Universitetsbibliotek
https://gup.ub.gu.se/publication/10783
or
Gothenburg University Library
https://gup.ub.gu.se/publication/10783?lang=en
> licentiate thesis

- doc/happy.xml
- examples/ErlParser.ly
- packages/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
- packages/codegen-common/happy-codegen-common.cabal
- packages/tabular/src/Happy/Tabular/LALR.lhs
- tests/precedence001.ly
doc/happy.xml
examples/ErlParser.ly
packages/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
packages/codegen-common/happy-codegen-common.cabal
packages/tabular/src/Happy/Tabular/LALR.lhs
tests/precedence001.ly
> fix more typos

- .readthedocs.yaml
> Vanilla Read The Docs configuration for the Happy docs

- .github/workflows/haskell-ci.yml
- happy.cabal
- packages/backend-glr/happy-backend-glr.cabal
- packages/backend-lalr/happy-backend-lalr.cabal
- packages/codegen-common/happy-codegen-common.cabal
- packages/frontend/happy-frontend.cabal
- packages/grammar/happy-grammar.cabal
- packages/tabular/happy-tabular.cabal
As you requested, @andreasabel
> CI against newer version of GHC 9.2 and 9.4

- packages/backend-lalr/src/Happy/Backend/LALR/ProduceCode.lhs
> Generate two spaces instead of tabs (#24)

- lib/data/HappyTemplate.hs
There were enough requests for a better panic message that we may as well deliver it.
Fixes #186.
> Better panic message, indicating that it's not the user's fault (#186)

- ChangeLog.md
- app/Main.lhs
> Implement --numeric-version (#301)

- happy.cabal
- lib/happy-lib.cabal
* [`happy-lib` candidate](https://hackage.haskell.org/package/happy-lib-2.1/candidate)
* [`happy` candidate](https://hackage.haskell.org/package/happy-2.1/candidate)
* [change log](https://hackage.haskell.org/package/happy-2.1/candidate/changelog)
> Prepare 2.1 release

- lib/backend-lalr/src/Happy/Backend/LALR.hs
- tests/Makefile
> Add Data.Tuple to Happy_Prelude in order to fix --debug build (#330)
